# Routes pour les Clients
api_client_register:
    path: /creerCompte
    controller: App\Controller\RegisterController::register
    methods: POST

api_login:
    path: /login
    controller: App\Controller\RegisterController::login
    methods: POST

api_client_profile:
    path: /profile
    controller: App\Controller\RegisterController::show
    methods: GET

api_client_update:
    path: /profile
    controller: App\Controller\RegisterController::update
    methods: PUT

api_client_verify:
    path: /verify
    controller: App\Controller\RegisterController::verifyAccount
    methods: POST